options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/tf-pipeline-492916/gemini-repo/app:$SHORT_SHA
      - app/

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_REGION}-docker.pkg.dev/tf-pipeline-492916/gemini-repo/app:$SHORT_SHA

  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - gemini-adk-agent
      - --image=${_REGION}-docker.pkg.dev/tf-pipeline-492916/gemini-repo/app:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=cloud-run-sa@tf-pipeline-492916.iam.gserviceaccount.com



images:
  - ${_REGION}-docker.pkg.dev/tf-pipeline-492916/gemini-repo/app:$SHORT_SHA

substitutions:
  _REGION: us-central1
